spring:
  data:
    mongodb:
      host: ENC(hfBIwfcmwuqPXkSxABqJ4Bw1lVTSYdt3)
      port: 27017
      database: ENC(qF9jt3azp8GUIk1m9fkOZ45FkVKm6hpZ)
      username: ENC(U9b7OmLUZ9Z5GPHkGOkFoA==)
      password: ENC(1PI6z4vKKl4w36lYhZfxhZwWeWHYOHUukDDkw8s/OUw=)
jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password: ${jasyptPassword}

slack.token: ENC(IVD2Sq2qSXByzUcZQMv6b6fQxnoSrn+dsKSdf9W4XwZdO3kjMX7AsRYz0kRJTrUZ4OdyOtIy1wUPCey04lzFYA==)