#mongodb:
#  uri: mongodb://localhost:27017/tft_service
#  dbname: tft_service

spring:
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    cache: false
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: true
